'''GITHUB-y et hatuk hartaka vortex mi proekti vra karoxen ashxatel tarber mardiq'''
'''es zut grumem mots lini'''
'''gity qashumenq granvumenq sarqumenq repositorya'''
'''skzbi hamar virtual enviroment enq qashum--- python3 -m venv venv, heto---- source venv/bin/activate'''
'''heto pip install --upgrade pip'''
'''cd enq linum mer fayli mej orinak es depqum cd lessons'''
'''kody greluc heto grumenq git status'''
'''heto git add u mer .py fayly for example (git add loop.py)'''
'''heto git -m commit 'stex grumenq coomment' '''
'''u verjiny git push'''